const replacements = [
  {
    name: "Bujia",
    marca: "NGK",
    imageUrl: "https://i.ibb.co/LnnX8JF/pngwing-com-1.png",
    puntuacionProm: 3,
    cantReseñas: 12,
    precio: 5000,
    descuento: false,
    fondo: "red",
  },
  {
    name: "Amortiguadores",
    marca: "Monroe",
    imageUrl: "https://i.ibb.co/LnnX8JF/pngwing-com-1.png",
    puntuacionProm: 2,
    cantReseñas: 5,
    precio: 3500,
    descuento: false,
    fondo: "blue",
  },
  {
    name: "Filtro de Aire",
    marca: "K&N",
    imageUrl: "https://i.ibb.co/LnnX8JF/pngwing-com-1.png",
    puntuacionProm: 4,
    cantReseñas: 1,
    precio: 2340,
    descuento: false,
    fondo: "red",
  },
  {
    name: "Batería",
    marca: "Moure",
    imageUrl: "https://i.ibb.co/LnnX8JF/pngwing-com-1.png",
    puntuacionProm: 5,
    cantReseñas: 9,
    precio: 5800,
    descuento: false,
    fondo: "blue",
  },
  {
    name: "Neumático",
    marca: "Pirelli",
    imageUrl: "https://i.ibb.co/LnnX8JF/pngwing-com-1.png",
    puntuacionProm: 3.5,
    cantReseñas: 46,
    precio: 1700,
    descuento: false,
    fondo: "red",
  },
  {
    name: "Kit de Transmisión",
    marca: "RK",
    imageUrl: "https://i.ibb.co/LnnX8JF/pngwing-com-1.png",
    puntuacionProm: 3,
    cantReseñas: 12,
    precio: 5000,
    descuento: false,
    fondo: "blue",
  },
  {
    name: "Pastillas de Frenos",
    marca: "Bendix",
    imageUrl: "https://i.ibb.co/LnnX8JF/pngwing-com-1.png",
    puntuacionProm: 1,
    cantReseñas: 1,
    precio: 3900,
    descuento: false,
    fondo: "red",
  },
  {
    name: "Filtro de Aceite",
    marca: "Fram",
    imageUrl: "https://i.ibb.co/LnnX8JF/pngwing-com-1.png",
    puntuacionProm: 3,
    cantReseñas: 112,
    precio: 10500,
    descuento: false,
    fondo: "blue",
  },
  {
    name: "Filtro de Combustible",
    marca: "Bosch",
    imageUrl: "https://i.ibb.co/LnnX8JF/pngwing-com-1.png",
    puntuacionProm: 4.5,
    cantReseñas: 8,
    precio: 3200,
    descuento: false,
    fondo: "red",
  },
  {
    name: "Lámpara Halógena",
    marca: "Osram",
    imageUrl: "https://i.ibb.co/LnnX8JF/pngwing-com-1.png",
    puntuacionProm: 3.8,
    cantReseñas: 15,
    precio: 1800,
    descuento: false,
    fondo: "blue",
  },
  {
    name: "Correa de Distribución",
    marca: "Dayco",
    imageUrl: "https://i.ibb.co/LnnX8JF/pngwing-com-1.png",
    puntuacionProm: 4.2,
    cantReseñas: 20,
    precio: 4500,
    descuento: false,
    fondo: "blue",
  },
  {
    name: "Limpiaparabrisas",
    marca: "Bosch",
    imageUrl: "https://i.ibb.co/LnnX8JF/pngwing-com-1.png",
    puntuacionProm: 3.5,
    cantReseñas: 10,
    precio: 2800,
    descuento: false,
    fondo: "red",
  },
  {
    name: "Termostato",
    marca: "Gates",
    imageUrl: "https://i.ibb.co/LnnX8JF/pngwing-com-1.png",
    puntuacionProm: 4,
    cantReseñas: 6,
    precio: 3600,
    descuento: false,
    fondo: "blue",
  },
  {
    name: "Espejo Retrovisor",
    marca: "TYC",
    imageUrl: "https://i.ibb.co/LnnX8JF/pngwing-com-1.png",
    puntuacionProm: 3.7,
    cantReseñas: 18,
    precio: 2500,
    descuento: false,
    fondo: "red",
  },
  {
    name: "Alternador",
    marca: "Bosch",
    imageUrl: "https://i.ibb.co/LnnX8JF/pngwing-com-1.png",
    puntuacionProm: 4.3,
    cantReseñas: 22,
    precio: 12000,
    descuento: false,
    fondo: "blue",
  },
  {
    name: "Radiador",
    marca: "Valeo",
    imageUrl: "https://i.ibb.co/LnnX8JF/pngwing-com-1.png",
    puntuacionProm: 4.5,
    cantReseñas: 18,
    precio: 8500,
    descuento: false,
    fondo: "red",
  },
  {
    name: "Bomba de Agua",
    marca: "SKF",
    imageUrl: "https://i.ibb.co/LnnX8JF/pngwing-com-1.png",
    puntuacionProm: 4,
    cantReseñas: 11,
    precio: 6800,
    descuento: false,
    fondo: "blue",
  },
  {
    name: "Filtro de Habitáculo",
    marca: "Mahle",
    imageUrl: "https://i.ibb.co/LnnX8JF/pngwing-com-1.png",
    puntuacionProm: 3.5,
    cantReseñas: 20,
    precio: 2600,
    descuento: false,
    fondo: "red",
  },
  {
    name: "Faros",
    marca: "Hella",
    imageUrl: "https://i.ibb.co/LnnX8JF/pngwing-com-1.png",
    puntuacionProm: 4.7,
    cantReseñas: 30,
    precio: 4500,
    descuento: false,
    fondo: "blue",
  },
  {
    name: "Tapa de Distribuidor",
    marca: "Delphi",
    imageUrl: "https://i.ibb.co/LnnX8JF/pngwing-com-1.png",
    puntuacionProm: 4.1,
    cantReseñas: 25,
    precio: 3100,
    descuento: false,
    fondo: "red",
  },
];

export default replacements;
